### ISSUE TITLE
New Error come about the CurrentSP !

### ISSUE THREAD

**Issue by nguoingoai** [mgierw/auto-foe#15]
![screen shot 2017-07-24 at 8 26 43 pm](https://user-images.githubusercontent.com/28948005/28525508-ad87aa68-70ae-11e7-8a2e-e394cf880e1b.png)

TypeError: Cannot read property 'currentSP' of undefined
    at checkStrategyPointOverflow (/auto-foe/server/CityProductionService.js:94:16)
    at _.filter.b (/auto-foe/server/CityProductionService.js:102:12)
    at arrayFilter (/auto-foe/node_modules/lodash/lodash.js:603:11)
    at Function.filter (/auto-foe/node_modules/lodash/lodash.js:9190:14)
    at interceptor (/auto-foe/node_modules/lodash/lodash.js:16970:35)
    at thru (/auto-foe/node_modules/lodash/lodash.js:8812:14)
    at /auto-foe/node_modules/lodash/lodash.js:4379:28
    at arrayReduce (/auto-foe/node_modules/lodash/lodash.js:704:21)
    at baseWrapperValue (/auto-foe/node_modules/lodash/lodash.js:4378:14)
    at LazyWrapper.lazyValue [as value] (/auto-foe/node_modules/lodash/lodash.js:1880:16)

**Comment by mgierw** [comment]
Commited some changes 97e825217dd22c4b9c67293afe9ed823d5733eff.

**Comment by ophott** [comment]
Thank you.....mgierw... It works..

**Comment by nguoingoai** [comment]
Great again !!, thanks you so much.
