### ISSUE TITLE
New error.. since game got updated today..

### ISSUE THREAD

**Issue by ophott** [mgierw/auto-foe#16]
[2017-07-26 14:16:14.079] [LOG]   Wystąpiły błędy
[2017-07-26 14:16:14.079] [LOG]   { Error: connect ECONNABORTED 162.217.207.19:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:14)
  code: 'ECONNABORTED',
  errno: 'ECONNABORTED',
  syscall: 'connect',
  address: '162.217.207.19',
  port: 443 }
[2017-07-26 14:16:15.520] [LOG]   Wystąpił błąd
[2017-07-26 14:16:15.520] [LOG]   { Error: connect ECONNABORTED 162.217.207.19:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:14)
  code: 'ECONNABORTED',
  errno: 'ECONNABORTED',
  syscall: 'connect',
  address: '162.217.207.19',
  port: 443 }

**Comment by ophott** [comment]
[2017-07-27 11:39:50.715] [LOG]   marioboss(us8): Wywołanie invokeGetData
[2017-07-27 11:39:54.887] [LOG]   marioboss(us8): Automatyczne przetwarzanie zgłosiło wyjątek
[2017-07-27 11:39:54.887] [LOG]   marioboss(us8): TypeError: Cannot read property 'currentSP' of undefined
    at checkStrategyPointOverflow (C:\Users\Mayank\Desktop\AutoFoe\server\CityProductionService.js:80:16)
    at _.filter.b (C:\Users\Mayank\Desktop\AutoFoe\server\CityProductionService.js:88:12)
    at arrayFilter (C:\Users\Mayank\Desktop\AutoFoe\node_modules\lodash\lodash.js:603:11)
    at Function.filter (C:\Users\Mayank\Desktop\AutoFoe\node_modules\lodash\lodash.js:9190:14)
    at interceptor (C:\Users\Mayank\Desktop\AutoFoe\node_modules\lodash\lodash.js:16970:35)
    at thru (C:\Users\Mayank\Desktop\AutoFoe\node_modules\lodash\lodash.js:8812:14)
    at C:\Users\Mayank\Desktop\AutoFoe\node_modules\lodash\lodash.js:4379:28
    at arrayReduce (C:\Users\Mayank\Desktop\AutoFoe\node_modules\lodash\lodash.js:704:21)
    at baseWrapperValue (C:\Users\Mayank\Desktop\AutoFoe\node_modules\lodash\lodash.js:4378:14)
    at LazyWrapper.lazyValue [as value] (C:\Users\Mayank\Desktop\AutoFoe\node_modules\lodash\lodash.js:1880:16)
