### ISSUE TITLE
auto-foe

### ISSUE THREAD

**Issue by w27003** [mgierw/auto-foe#5]
I get such a err, what i do wrong ?

C:\Users\MAte\Desktop\auto-foe-master>node server-start.js
module.js:472
    throw err;
    ^

Error: Cannot find module 'moment'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\MAte\Desktop\auto-foe-master\server-start.js
:1:76)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

C:\Users\MAte\Desktop\auto-foe-master>

**Comment by DavidMoritz** [comment]
Did you run "npm install"?

**Comment by w27003** [comment]
yes, got it, that was the case ;) thx, works awesome

**Comment by w27003** [comment]
Hello,
I have question/sugestion to your awesome bot:)
The thing is Development Points(DP) and their spending, I have noticed that
when u acquire expedition chest there is % chance to get DP and while you
have already acumulated around 9-10 DP then when u get mentioned reward u
will actualy lose 5 or 10 DP, dunno if the same goes with great buildings
which produce DP. If I'am correct and it wouldn't be big hassle for you,
small update would be very appreciated :).
I thought about simple mechanic like playing niormal manualy start some
research by spending 1DP in prefered tech. After that bot would recognize
marked technology and fullfill it untill end. After that it would spend DP
on others "marked" technologies. If technology is not marked by already
spent point it would start acumulating them?
Whats your thought ?
Best regards
MK

2017-05-07 20:34 GMT+02:00 DavidMoritz <notifications@github.com>:

**Comment by DavidMoritz** [comment]
That sounds like a great improvement! Please submit a pull request with
what you had in mind!
