### ISSUE TITLE
node start error

### ISSUE THREAD

**Issue by ghost** [mgierw/auto-foe#7]
```
 node server-start.js 

/root/Downloads/auto-foe-master/server-start.js:4
	formatter: () => moment().tz('Europe/Warsaw').format('YYYY-MM-DD HH:mm:ss.SSS
	            ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by DavidMoritz** [comment]
It looks like you are not using a current version of node. Try updating to
version 6.10.3
