### ISSUE TITLE
Error when start server-start.js

### ISSUE THREAD

**Issue by ghost** [mgierw/auto-foe#8]
The settings.json 
```
{
        "accounts": [{
                "loginType": "game",
                "username": "myusername",
                "password": "mybase64encodepassword",
                "lang": "en",
                "world": "en5"
        }]
}
```

[2017-05-23 17:49:43.378] [LOG]   doJQueryRequest: https://pl.forgeofempires.comundefined
[2017-05-23 17:50:46.679] [LOG]   Wystąpiły błędy
[2017-05-23 17:50:46.679] [LOG]   { Error: connect ETIMEDOUT 125.235.4.59:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '125.235.4.59',
  port: 443 }
[2017-05-23 17:50:46.685] [LOG]   Wystąpił błąd

[2017-05-23 17:50:46.685] [LOG]   { Error: connect ETIMEDOUT 125.235.4.59:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '125.235.4.59',
  port: 443 }
[2017-05-23 17:50:46.687] [ERROR] Error: connect ETIMEDOUT 125.235.4.59:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
[2017-05-23 17:50:46.690] [ERROR] (node:1986) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property '$' of undefined

**Comment by DavidMoritz** [comment]
Three things can be at play here.
1. Seeing your first log points out to me a small bug in the code. This can be resolved by changing line 52 of login-helper to say "//en.forge..." rather than "//pl.forge..." or you can pull the latest from master
2. I currently don't know why it says "undefined" after the jQueryRequest, but try changing "game" to "normal" in the settings.json
3. You may not have permissions to access the location. The "UnhandledPromiseRejectionWarning" suggests this may be the case. Verify that you are able to access the page "https://en.forgeofempires.com" on the same computer within a browser

Hope that helps!

**Comment by ghost** [comment]
Thanks you , your script are running :)) , When script are runnig , can I open game in browser to see what happen ?

**Comment by DavidMoritz** [comment]
You can try, but it will log you out automatically once the script does
anything. Better is to use the built in monitoring feature running on
localhost:3000

**Comment by ghost** [comment]
Are there any way to enable or disable your script feature ?
Some thing like , I want your script just collect and build resource: coins , supplies (can select 1hour or 4h product build) , goods(Can select 1h or 4h or 1day build). Not using forge point , not create trading goods, not scout a province. Because some time there is Events Quest anh I want to save forge point for this Quest

**Comment by DavidMoritz** [comment]
Yes, actually, this is a feature I am working on. Those were exactly the
things I wanted to avoid as well and got it working locally, but haven't
pushed my changes up yet. If you want to do what I did, go into the code
and carefully remove the references to campaign Service, trade Service. The
forge point is a little more complicated, but if you find the spots that
say "spend 1 point" and comment out the code immediately after

**Comment by ghost** [comment]
Thanks you so much , I will wait to the new release .

**Comment by DavidMoritz** [comment]
@phaothu Please try out the new branch called "feature/options" and be our tester. Let us know if it works for you!
https://github.com/mgierw/auto-foe/blob/feature/options/index.js

**Comment by ghost** [comment]
I replcae index.js with the new in https://github.com/mgierw/auto-foe/blob/feature/options/index.js
Here is the result

```
[2017-05-25 05:34:20.270] [LOG]   extractFlashVar("string_basepath") = "https://foeen.innogamescdn.com/"
[2017-05-25 05:34:20.271] [LOG]   myusername(en5): Call invokeGetData
/home/auto-foe-master/index.js:99
		if(userData.services[service.getServiceName()] != false) return service.process;
		                    ^

TypeError: Cannot read property 'CityProductionService' of undefined
    at checkOption (/home/auto-foe-master/index.js:99:23)
    at processAutomaticActions (/home/auto-foe-master/index.js:104:10)
    at Timeout.timeoutFunction [as _onTimeout] (/home/auto-foe-master/index.js:66:4)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by DavidMoritz** [comment]
You need to pull the entire feature, not just one file. The settings.json
is different also

**Comment by DavidMoritz** [comment]
https://github.com/mgierw/auto-foe/blob/feature/options/userdata/settings.json

**Comment by ghost** [comment]
I am not familiar with Git so just show me the steps to do , I usually download the zip file and work on it :) .  By the way I view the log file and never see the LOG about the get gold from buildings, get supplies from production buildings, get goods from good building or the same with action build .

One more question : There are some technology like Multistory Houses need 600 diamond to unlock , I do not buy diamond , so your script can use forge point to next to other technology or will stuck in that ?

**Comment by mgierw** [comment]
1. Getting gold/supplies and starting production is not logged because it is very often task.
2. "Diamond" technologies don't block other technologies to be revealed.

**Comment by DavidMoritz** [comment]
@ghost the only thing you need to do is change your settings.json file to reflect the one I linked to that now has the services options.
https://github.com/mgierw/auto-foe/blob/feature/options/userdata/settings.json
Please try it out and let us know what you think

**Comment by nguoingoai** [comment]
"ResearchService" : false . It's ok not using forge point to research .

**Comment by DavidMoritz** [comment]
Good! Are there any other services you want to test by setting then
to"false"?

**Comment by nguoingoai** [comment]
Not yet now . Because all the others should be alway auto :) . 
One feature I thinks very need is auto train soldier , unlock soldier. Your script don't have this feature

**Comment by yobytae** [comment]
[2017-11-14 15:45:04.624] [LOG]   Login using a game account
[2017-11-14 15:45:04.624] [LOG]   doJQueryRequest: https://us.forgeofempires.com/
[2017-11-14 15:45:04.649] [LOG]   Listening at the port 3000, na adresie 127.0.0.1
[2017-11-14 15:45:39.544] [LOG]   submitForm: Sending login data…
[2017-11-14 15:45:39.547] [LOG]   Akcja formularza nie jest pełnym URL-em, doklejam protokół i hosta
[2017-11-14 15:45:41.124] [LOG]   Wynik: false, url: undefined, id gracza: 
[2017-11-14 15:45:41.124] [LOG]   url = https://us.forgeofempires.comundefined
[2017-11-14 15:45:41.125] [LOG]   doJQueryRequest: https://us.forgeofempires.comundefined
